services:
  image_build:
    # [build]
    # service to run rosdep update && colcon build
    # TARGET_TAG : tag of build source image "acsl-common"
    # TAG : output image tag 
    # Example：TARGET_TAG=target TAG=output docker compose build common 
    #  kasekiguchi/acsl-common:target  =>  kasekiguchi/acsl-common:output
    image: kasekiguchi/acsl-common:${OTAG:-build}
    build:
      dockerfile: dockerfiles/dockerfile.${DF:-build} # 実行するdockerfile指定
      args:
        - BASE_IMAGE=${BASE_IMAGE:-kasekiguchi/acsl-common:${ITAG:-base}} # 元となるimage
        # for x86 : osrf/ros:humble-desktop
        # for arch : arm64v8/ros:humble

  common:
    # [up]
    # HOSTNAME : host pc name
    # CONTAINER_NAME : output container name
    # ROS_LAUNCH : shell script name containing ros2 start command in the container
    # LARGS : arguments to the ROS_LAUNCH file
    # ID : ROS_DOMAIN_ID
    tty: true
    privileged: true # privileged mode
    image: kasekiguchi/acsl-common:${TAG:-base}
    hostname: D${HOSTNAME:-}
    container_name: ${CONTAINER_NAME:-dev}
    entrypoint:
      [
        "/usr/local/bin/dumb-init", # for quick stop of the container
        "/common/scripts/entrypoint.sh" # execute at the container up
      ]
    command:
      # arguments for entrypoint.sh (refer to the entrypoint.sh file)
      [
        "/common/ros_launcher/${ROS_LAUNCH:-launch_dev.sh}",
        "${LARGS:-None}" # launch arguments
      ]
    working_dir: /root/ros2_ws
    environment:
      # set environment variable on docker 
      - PROJECT=${PROJECT}
      - CONTAINER_NAME=${COMPOSE_PROJECT_NAME:-dev} #${CONTAINER_NAME:-dev}
      - TAG=${TAG:-${PROJECT}_build}
      - HOST_USER=$LOGNAME # deprecate 
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID} # set project unique id
      # - SSH_PORT=3222 # to activate SSH, following ports should be active :  User=root Password=root
      #ports:
      #  - 3222:3222

    volumes:
      # bind "host folder":"docker folder"
      - ./common:/common # common scripts
      - /dev:/dev # GPIO and USB devices
      - vscode-server:/root/.vscode-server # VScode setting (preserve VScode extension)
      - ./../2_ros_packages:/root/ros2_ws/src/ros_packages
        # ros packages
        # - ./common/rules/custom.rules:/etc/udev/rules.d/90-custom.rules # custom configuration for USB device

    # ▼ use host network to connect external device
    #  Caution : set ROS_DOMAIN_ID properly to separate the namespace in ROS2
    network_mode: host
    ipc: host

    device_cgroup_rules:
      # a (all), c (char), or b (block) 
      # https://www.kernel.org/doc/Documentation/admin-guide/devices.txt
      # require for Realsense
      - 'c 81:* rmw' # video4linux
      - 'c 189:* rmw' # USB serial converters - alternate devices

volumes:
  vscode-server: # named volume : preserve contents independent from containers
