#! /usr/bin/bash

source ~/ros2/1_docker/common/scripts/super_echo
export PROJECT=whill
if [ $# -eq 1 ]; then
  case ${1} in
  "all")
    dsbuild base lidar microros gnss mocap t265
    build_project ${PROJECT} whill_driver acsl_interfaces status_checker
    ;;
  "ros")
    build_project ${PROJECT} ${@:2:($# - 1)}
    ;;
  "docker")
    dsbuild ${@:2:($# - 1)}
    ;;
  *)
    build_project ${PROJECT} ${@:2:($# - 1)}
    ;;
  esac
else
  build_project ${PROJECT} whill_driver acsl_interfaces status_checker
fi
