#! /usr/bin/bash

source ~/.bashrc

dsbuild base microros
dsbuild base gnss build
dsbuild base rplidar build
dsbuild base mocap build
dsbuild base velodyne build
dsbuild base tb3 build
dsbuild base t265
dsbuild base realsense

# 20240701 一通りbuildできることを確認
