#! /usr/bin/bash

# #1 : project name
# #2- : build target packages

source $ACSL_ROS2_DIR/4_docker/common/scripts/super_echo
if [ $# -ge 1 ]; then
  #packs=${@:1:($# - 1)}
  packs=$@
else
  packs=$(my_packages)
fi

gecho "build own ros packages"
#PACK=$(my_packages)
#LARGS=$PACK ROS_LAUNCH=launch_build.sh TAG=${1} docker compose up common -d
#echo $TAG
#TAG=${TAG} dup build $packs

fx86=$(uname -a | grep x86)
if [[ -n $fx86 ]]; then
  x86="_x86"
else
  x86=""
fi

exist_image=$(docker images kasekiguchi/acsl-common:image_${PROJECT}${x86} | grep ${PROJECT}${x86})
if [[ -z $exist_image ]]; then
  recho "create image_${PROJECT}${x86} image first"
else
  dup build $packs
  # acsl-common:$TAG を build コンテナとしてcommon サービスで起動
  # 中で　launch_build.sh　を実行し自作パッケージをcolcon buildする

  dlogs build
  gecho "docker commit : from build container to image_${PROJECT}${x86} tagged image"
  dcommit build image_${PROJECT}${x86}
  gecho "remove build container"
  drm build
fi
