#! /usr/bin/bash

source ~/ros2/1_docker/common/scripts/super_echo
export PROJECT=megarover
if [ $# -eq 1 ]; then
  case ${1} in
  "all")
    dsbuild base rplidar microros t265
    #build_project ${PROJECT} acsl_interfaces
    ;;
  "ros")
    #build_project ${PROJECT} ${@:2:($# - 1)}
    ;;
  "docker")
    dsbuild ${@:2:($# - 1)}
    ;;
  *)
    # build_project ${PROJECT} ${@:2:($# - 1)}
    ;;
  esac
  #else
  #build_project ${PROJECT}
fi
