#! /usr/bin/bash
# Build docker image
# [Usage] arguments number <= 3
# dbuild  : build image_${PROJECT} from base image using dockerfile.build
# dbuild drone : build image_drone from base image using dockerfile.build ( verbose )
# dbuild A B : build image B from image A using dockerfile.build
# dbuild A B DF : build image B from image A using DF
cd ~/ros2/1_docker/
source ~/ros2/1_docker/common/scripts/super_echo
if [ $# -eq 3 ]; then
  ITAG=$1
  OTAG=$2
  DF=$3
elif [ $# -eq 2 ]; then
  ITAG=${1}
  OTAG=${2}
  DF=build
elif [ $# -eq 1 ]; then
  ITAG=base
  OTAG=image_${1}
  DF=build
else
  recho "Confirm setup.sh is completed by bash setup.sh PROJECT_NAME at 0_host_commands"
  ITAG=base
  OTAG=image_${PROJECT}
  DF=build
fi
gecho "build $OTAG FROM $ITAG using dockerfile.$DF"
ITAG=$ITAG OTAG=$OTAG DF=$DF docker compose build image_build --no-cache
