#! /usr/bin/bash

cd $ACSL_ROS2_DIR/4_docker/
echo $(pwd)
source $ACSL_ROS2_DIR/4_docker/common/scripts/super_echo

if [ $# -eq 0 ]; then
  echo "Build docker image"
  echo "[Usage] arguments number <= 3"
  echo "dbuild  : build image_${PROJECT}${TARGET} from base image using dockerfile.build"
  echo "dbuild drone : build image_drone from base image using dockerfile.build ( verbose )"
  echo "dbuild A B : build image B from image A using dockerfile.build"
  echo "dbuild A B DF : build image B from image A using DF"
else
  if [ $# -eq 3 ]; then
    ITAG=$1
    OTAG=$2
    DF=$3
  elif [ $# -eq 2 ]; then
    ITAG=${1}
    OTAG=${2}
    DF=build
  elif [ $# -eq 1 ]; then
    ITAG=base
    OTAG=image_${1}
    DF=build
  fi
  fx86=$(uname -a | grep x86)
  if [[ -n $fx86 ]]; then
    ITAG=${ITAG%_x86}_x86
    OTAG=${OTAG%_x86}_x86
  fi
  if [[ -e $ACSL_ROS2_DIR/3_dockerfiles/dockerfile.${DF} ]]; then
    DF=$ACSL_ROS2_DIR/3_dockerfiles/dockerfile.${DF}
  fi
  if [[ -e $ACSL_WORK_DIR/3_dockerfiles${TARGET}/dockerfile.${DF} ]]; then
    DF=$ACSL_WORK_DIR/3_dockerfiles${TARGET}/dockerfile.${DF}
  fi
  gecho "DBUILD: build tag:$OTAG FROM tag:$ITAG using $DF"
  ITAG=$ITAG OTAG=$OTAG DF=$DF docker compose build image_build # --no-cache
fi
