#! /usr/bin/bash
# docker commit
# it works in both HOST and CONTAINER
if [ $# -eq 1 ]; then
  STAG=$TAG # works only in CONTAINER
  ETAG=$1
else
  STAG=$1
  ETAG=$2
fi
echo "Build image from $STAG to $ETAG"

if [ ${HOSTNAME:0:1} == "D" ]; then
  ssh -o StrictHostKeyChecking=no $HOST_USER@172.17.0.1 "docker commit $STAG kasekiguchi/acsl-common:$ETAG"
else
  docker commit $STAG kasekiguchi/acsl-common:$ETAG
fi
