#! /usr/bin/bash

# cd $ACSL_ROS2_DIR/4_docker
# COMPOSE_PROJECT_NAME=${1,,}_${PROJECT,,}${TARGET,,} docker compose exec common bash
if [[ "$1" =~ ^--image= ]]; then
  shift
fi
docker exec -it ${1,,} bash
