#! /bin/bash

source ~/ros2/1_docker/common/scripts/super_echo
if [ $# -ge 1 ]; then
  packs=$@
  TAG=drone_build
else
  packs=$(my_packages)
  TAG=drone_build
  gecho "build third party packages"
  TARGET_TAG=drone_ros2 TAG=${TAG} docker compose build common
#--no-cache
fi

gecho "build own ros packages"
#PACK=$(my_packages)
#LARGS=$PACK ROS_LAUNCH=launch_build.sh TAG=drone docker compose up common -d

TAG=${TAG} dup build $packs
# acsl-common:$TAG を build コンテナとして起動
# 中で　launch_build.sh　を実行

dlogs build
gecho "docker commit : from build container to drone_build tagged image"
dcommit build drone_build
gecho "remove build container"
drm build
