#! /usr/bin/bash
# dsbuild = sequential dbuild
# prepare : dockerfile."$EXT1", dockerfile."$EXT2", ..., dockerfile."$EXT"
# dsbuild "$EXT1" "$EXT2" ... "$EXT"
# output : kasekiguchi/acsl_common:"$EXT"

# sequential build for docker
source ~/acsl_ros2/1_docker/common/scripts/super_echo

echo "##########################################"
gecho "Build image_${PROJECT}"
echo "##########################################"
if [ $# -ge 1 ]; then
  ITAG=$1
  for OTAG in ${@:2:($# - 1)}; do
    #gecho "Build $OTAG from $ITAG using dockerfile.$OTAG"
    if [ $OTAG == "build" ]; then
      dbuild $ITAG $ITAG $OTAG # tagを変更せず上書き
      ITAG=$ITAG
    else
      dbuild $ITAG $OTAG $OTAG
      ITAG=$OTAG
    fi
  done
else
  lsit=$(ls ~/acsl_ros2/1_docker/dockerfiles)
  echo "Possible docker build items : "
  echo "${list[@]}" | sed -e "s/dockerfile.//g" -e "s/base//" -e "s/build//"
fi
