#! /usr/bin/bash
# [Usage 1]
# >set_bashrc key value
# if key is not in .bashrc
# add key=value to .bashrc
# else replace value
# [Usage 2]
# >set_bashrc key
# if key is not in .bashrc
# add key to .bashrc
# else do nothing

key=$1
check=$(cat ~/.bashrc | grep "$key")
if [[ $# > 1 ]]; then 
    value=${@:2:($# - 1)}
    if [[ -z $check ]]; then # .bashrc に存在しない場合
        echo "ADD : $key=$value"
        echo "$key=$value" >>~/.bashrc
    else
        echo "REPLACE : $key=$value"
        sed -i -e "/$key/c $key=$value" ~/.bashrc
    fi
else
    if [[ -z $check ]]; then # .bashrc に存在しない場合
        echo "ADD : $key"
        echo "$key" >>~/.bashrc
    fi
fi