ARG BASE_IMAGE
ARG ROS_PACKAGE
ARG SEPARATE
ARG ROS_DISTRO
FROM ${BASE_IMAGE} as base

SHELL [ "/bin/bash","-c" ]

#&& git clone --depth 1 https://github.com/CreedyNZ/rplidar_ros2.git -b ros2
RUN mkdir -p ~/ros2_ws/src && cd ~/ros2_ws/src \
  && git clone --depth 1 https://github.com/Slamtec/rplidar_ros.git -b ros2 
# rplidar_ros は colcon build でwarningでるが問題ない

