docker pull ros:foxy
docker run --name base2004 -it ros:foxy bash

apt update && apt install -y \
  python3-numpy \
  python3-scipy \
  python3-pandas \
  python3-numexpr \
  python3-matplotlib \
  python3-serial \
  python3-tk \
  python3-pexpect \
  python3-rosdep \
  python3-pip

pip3 install -U dumb-init \
  && apt autoremove -y \
  && apt clean \
  && rm -rf /var/lib/apt/lists/* 

mkdir -p ~/ros2_ws/src 

docker commit base2004 kasekiguchi/acsl-common:base2004
