#! /usr/bin/bash
# required by build_project
if [ ${HOSTNAME:0:1} == "D" ]; then
  ros_packages=$(ls ~/ros2_ws/src/ros_packages)
else
  ros_packages=$(ls ~/ros2/2_ros_packages)
fi

echo ${ros_packages/README _ROS.md/}
