#! /bin/bash
export PROJECT=$1
ACSL_ROS2_DIR=$(
  cd $(dirname $0)
  cd ../
  pwd
)
chmod -R a+x $ACSL_ROS2_DIR/0_host_commands/scripts
chmod -R a+x $ACSL_ROS2_DIR/1_docker/common/scripts

if [[ -z $(cat ~/.bashrc | grep ORGPATH) ]]; then
  $ACSL_ROS2_DIR/0_host_commands/scripts/set_bashrc "export ORGPATH" $PATH
else
  source ~/.bashrc
  export PATH="$ORGPATH"
fi
export PATH="$PATH:$ACSL_ROS2_DIR/1_docker/common/scripts:$ACSL_ROS2_DIR/0_host_commands/scripts"
source $ACSL_ROS2_DIR/1_docker/common/scripts/super_echo
set_bashrc "source $ACSL_ROS2_DIR/1_docker/common/scripts/super_echo"
set_bashrc "export PATH" $PATH
set_bashrc "alias home" "'source home.sh'"
set_bashrc "export PROJECT" $PROJECT
set_bashrc "export ACSL_ROS2_DIR" $ACSL_ROS2_DIR
if [ $# -eq 2 ]; then
  RID=$2
else
  RID=$(cat $ACSL_ROS2_DIR/0_host_commands/project_launcher/ros2_id_list | grep $PROJECT | awk '{print $NF}')
fi
set_bashrc "export ROS_DOMAIN_ID" $RID

echo "Do following command"
gecho "source ~/.bashrc"
