#! /bin/bash
ACSL_WORK_DIR=$1
export PROJECT=$2
ACSL_ROS2_DIR=$(
  cd $(dirname $0)
  cd ../
  pwd
)
cd $ACSL_ROS2_DIR
chmod -R a+x $ACSL_ROS2_DIR/0_host_commands/scripts
chmod -R a+x $ACSL_ROS2_DIR/4_docker/common/scripts

if [[ -z $(cat $ACSL_ROS2_DIR/bashrc | grep ORGPATH) ]]; then
  $ACSL_ROS2_DIR/0_host_commands/scripts/set_bashrc "export ORGPATH" $PATH
else
  source $ACSL_ROS2_DIR/bashrc
  export PATH="$ORGPATH"
fi
export PATH="$PATH:$ACSL_ROS2_DIR/4_docker/common/scripts:$ACSL_ROS2_DIR/0_host_commands/scripts"
source $ACSL_ROS2_DIR/4_docker/common/scripts/super_echo
set_bashrc "source $ACSL_ROS2_DIR/4_docker/common/scripts/super_echo"
set_bashrc "export PATH" $PATH
set_bashrc "alias home" "'source home.sh'"
set_bashrc "export PROJECT" $PROJECT
set_bashrc "export ACSL_ROS2_DIR" $ACSL_ROS2_DIR
set_bashrc "export ACSL_WORK_DIR" $ACSL_WORK_DIR
if [ $# -eq 3 ]; then
  RID=$3
else
  RID=$(cat $ACSL_ROS2_DIR/0_host_commands/ros2_id_list | grep $PROJECT | awk '{print $NF}')
fi
set_bashrc "export ROS_DOMAIN_ID" $RID

echo "Do following command"
gecho "source $ACSL_ROS2_DIR/bashrc"
