#! /bin/bash

# [systemd] generate project_launch.service and project_launch.sh
# LAUNCH_FILE=$1
# 注意：systemd は rootで実行されるので ~ が使えないため、sedでフルパスを指定
source $ACSL_ROS2_DIR/4_docker/common/scripts/super_echo
gecho "Setup SYSTEMD"

sed -e "s|ACSL_WORK_DIR|$ACSL_WORK_DIR|g" $ACSL_ROS2_DIR/0_host_commands/project_launch_service >project_launch.service
sed -i "s|ACSL_ROS2_EXEC|$1|" project_launch.service
sed -i "s|ACSL_ROS2_DIR|$ACSL_ROS2_DIR|" project_launch.service
sudo chmod a+x project_launch.service

sed -i "s|\$ACSL_ROS2_DIR|$ACSL_ROS2_DIR|g" project_launch*.sh
sudo chmod a+x project_launch*.sh

sed -e "s|export ||g" $ACSL_ROS2_DIR/bashrc >$ACSL_ROS2_DIR/bashrc_systemd
if [[ -f /etc/systemd/system/project_launch.service ]]; then
  sudo rm /etc/systemd/system/project_launch.service
fi
sudo mv project_launch.service /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl enable project_launch
sudo systemctl start project_launch
