#! /usr/bin/bash +x

# cd /homedir/ros2/1_docker
# COMPOSE_PROJECT_NAME=bos CONTAINER_NAME=bos TAG=bos_build ID=21519 LARGS=robot ROS_LAUNCH=launch_bos_robot.sh docker compose up common -d

source /homedir/.bashrc

# export PROJECT=megarover
# export ROS_DOMAIN_ID=23 # Megarover => M = 77 @ASCII
# if [[ -z $(cat /homedir/.bashrc | grep ROS_DOMAIN_ID) ]]; then
#   echo "export ROS_DOMAIN_ID=$ROS_DOMAIN_ID" >>/homedir/.bashrc
# else
#   sed -i "s/ROS_DOMAIN_ID=.*\$/ROS_DOMAIN_ID=$ROS_DOMAIN_ID/" /homedir/.bashrc
# fi
cd /homedir/ros2/1_docker
../0_host_commands/scripts/dup t265
../0_host_commands/scripts/dup rplidar
../0_host_commands/scripts/dup microros
