#! /usr/bin/bash
# = exec $@ in container
# https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools/Using-Rqt-Console/Using-Rqt-Console.html
if [ ${HOSTNAME:0:1} == "D" ]; then
  cd /root/ros2_ws/
  source /opt/ros/${ROS_DISTRO}/setup.bash
  echo $@
  eval "$@"
else
  #str=$(dps | grep "dev${TARGET} " | grep Up)
  str=$(dps | grep -v Exited | awk '{print $NF}' | sed -e 's/NAMES//' | grep ${1})
  if [[ -z $str ]]; then
    dup dev${TARGET}
    container=dev${TARGET}
    cmd=$@
  else
    container=${str}
    cmd=${@:2:($# - 1)}
  fi
  source $ACSL_ROS2_DIR/4_docker/common/scripts/super_echo
  gecho IN:${container,,} RID:${ROS_DOMAIN_ID} PROJECT:${PROJECT}${TARGET}${x86}
  #_${PROJECT,,}${TARGET,,}
  COMPOSE_PROJECT_NAME=${container,,}_${PROJECT,,}${TARGET,,} docker compose exec common /common/scripts/Dcmd ${cmd[@]}
fi
