#! /usr/bin/bash
ssh -o StrictHostKeyChecking=no $HOST_USER@172.17.0.1 "export x86=\"$x86\"; export PROJECT=$PROJECT; export TARGET=\"$TARGET\"; export ROS_DOMAIN_ID=$ROS_DOMAIN_ID; export PATH=\"$HOST_PATH\"; export ACSL_WORK_DIR=\"$ACSL_WORK_DIR\"; export ACSL_ROS2_DIR=\"$ACSL_ROS2_DIR\"; export DISPLAY=\"$DISPLAY\"; $@"
# -XYC
