#! /usr/bin/bash
# required by build_project
if [ ${HOSTNAME:0:1} == "D" ]; then
  ros_packages=$(ls ~/ros2_ws/src/ros_packages)
else
  ros_packages=$(grep -RhoP '(?<=<name>)[^<]+' $ACSL_WORK_DIR/2_ros_packages  | sort -u)
fi

echo ${ros_packages/README_ROS.md/}
