#! /usr/bin/bash
# this works only in docker container
. /opt/ros/${ROS_DISTRO}/setup.bash

cd /root/ros2_ws/
source /root/.venv/bin/activate
source /opt/ros/${ROS_DISTRO}/setup.bash
python3 -m colcon build --parallel-workers $(($(nproc)-1)) --cmake-clean-cache