#! /usr/bin/bash

if [ ${HOSTNAME:0:1} == "D" ]; then
  cd /root/ros2_ws/
  source install/setup.bash
  if [ $# -ge 1 ]; then
    com=$@
  else
    com=list
  fi
  ros2 topic $com
else
  str=$(dps | grep dev | grep Up)
  if [[ -z $str ]]; then
    dup dev
  fi
  COMPOSE_PROJECT_NAME=dev_${PROJECT} docker compose exec common /common/scripts/rtopic $@
fi
